name: Build Release

on: release

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code into the Go Module directory
      uses: actions/checkout@master
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@master
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GORELEASE_GITHUB_TOKEN }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_PARAMETER_NAME: ${{ secrets.AWS_PARAMETER_NAME }}
        GOARCH: amd64
        GOOS: linux
        EXTRA_FILES: "LICENSE"
