name: Build Release

on:
  push:
    tags:
      - "*"

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code into the Go Module directory
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Write signing key to disk
      run: 'echo "$COSIGN_KEY" > cosign.key'
      shell: bash
      env:
        COSIGN_KEY: ${{ secrets.COSIGN_PVT_KEY }}
    - name: Setup cosign
      uses: sigstore/cosign-installer@v2.0.0
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@master
      with:
        distribution: goreleaser
        version: ${{ env.GITHUB_REF_NAME }}
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GORELEASE_GITHUB_TOKEN }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_PARAMETER_NAME: ${{ secrets.AWS_PARAMETER_NAME }}
